/* WEEKDAY */
INSERT INTO WEEKDAY (WEEKDAYID, NAME) VALUES ('1', 'Poniedzialek');
INSERT INTO WEEKDAY (WEEKDAYID, NAME) VALUES ('2', 'Wtorek');
INSERT INTO WEEKDAY (WEEKDAYID, NAME) VALUES ('3', 'Sroda');
INSERT INTO WEEKDAY (WEEKDAYID, NAME) VALUES ('4', 'Czwartek');
INSERT INTO WEEKDAY (WEEKDAYID, NAME) VALUES ('5', 'Piatek');
INSERT INTO WEEKDAY (WEEKDAYID, NAME) VALUES ('6', 'Sobota');
INSERT INTO WEEKDAY (WEEKDAYID, NAME) VALUES ('7', 'Niedziela');

/* STUDENT GROUP */
INSERT INTO STUDENTGROUP (GROUPID, NAME) VALUES ('1', '100');
/* STUDENT */
INSERT INTO STUDENT (INDEXNUMBER, AGE, MAIL, NAME, PASSWORD, PHONENUMBER, SURNAME, FIELDOFSTUDY, GROUPID)
VALUES ('1', '20', 'testMail@gmail.com', 'testName', 'testPass', '123456789', 'testSurname', 'testFOF', '1');

/* SUBJECT */
INSERT INTO SUBJECT (SUBJECTID, NAME) VALUES ('100', 'testName');
INSERT INTO SUBJECT (SUBJECTID, NAME) VALUES ('200', 'testName');

/* TEACHER */
 INSERT INTO TEACHER (TEACHERID, AGE, MAIL, NAME, PASSWORD, PHONENUMBER, SURNAME)
 VALUES ('2', '40', 'teacherMail@gmail.com', 'testName', 'testPass', '123456789', 'testSurname');

/* MARK */
INSERT INTO MARK (MARKID, VALUE, INDEXNUMBER, SUBJECTID, TEACHERID) VALUES ('1', '3', '1', '100', '2');
INSERT INTO MARK (MARKID, VALUE, INDEXNUMBER, SUBJECTID, TEACHERID) VALUES ('2', '5', '1', '100', '2');

