DROP TABLE exam CASCADE CONSTRAINTS;
DROP TABLE StudentGroup CASCADE CONSTRAINTS;
DROP TABLE lesson CASCADE CONSTRAINTS;
DROP TABLE mark CASCADE CONSTRAINTS;
DROP TABLE officeemployee CASCADE CONSTRAINTS;
DROP TABLE proposal CASCADE CONSTRAINTS;
DROP TABLE student CASCADE CONSTRAINTS;
DROP TABLE subject CASCADE CONSTRAINTS;
DROP TABLE teacher CASCADE CONSTRAINTS;
DROP TABLE timetable CASCADE CONSTRAINTS;
DROP TABLE weekday CASCADE CONSTRAINTS;

DROP SEQUENCE group_seq; 
DROP SEQUENCE proposal_seq;
DROP SEQUENCE subject_seq;
DROP SEQUENCE exam_seq;
DROP SEQUENCE timetable_seq;
DROP SEQUENCE lesson_seq;
DROP SEQUENCE mark_seq;