INSERT INTO WEEKDAY (WEEKDAYID, NAME) VALUES ('1', 'Poniedzialek');
INSERT INTO WEEKDAY (WEEKDAYID, NAME) VALUES ('2', 'Wtorek');
INSERT INTO WEEKDAY (WEEKDAYID, NAME) VALUES ('3', 'Sroda');
INSERT INTO WEEKDAY (WEEKDAYID, NAME) VALUES ('4', 'Czwartek');
INSERT INTO WEEKDAY (WEEKDAYID, NAME) VALUES ('5', 'Piatek');
INSERT INTO WEEKDAY (WEEKDAYID, NAME) VALUES ('6', 'Sobota');
INSERT INTO WEEKDAY (WEEKDAYID, NAME) VALUES ('7', 'Niedziela');